### PR TITLE
fix: product JSON generation (EcoscoreData related)

### LINKED ISSUE #70: Product JSON generation broken due to problem with EcoscoreData
The Product JSON generation is broken. In particular, the `ecoscore_data` field is not converted into JSON when the `Product.toJson` method is called.

The problem can be demonstrated using the following test, which is expected to pass but currently doesn't with version 0.3.14+1 of the openfoodfacts-dart SDK.

```dart
import 'package:flutter_test/flutter_test.dart';
import 'package:openfoodfacts/model/EcoscoreData.dart';
import 'package:openfoodfacts/model/Product.dart';

void main() {
  test('Product/EcoscoreData Json bug', () {
    final product = Product();
    product.productName = 'TestProduct';
    final ecoscoreData = EcoscoreData();
    ecoscoreData.grade = 'x';
    product.ecoscoreData = ecoscoreData;
    final productJson = product.toJson();
    assert(!(productJson['ecoscore_data'] is EcoscoreData));
  });
}
```
I expect this to be related to #63. @FredJul do you know what is up?

### PR DESCRIPTION
**Pull request by peterwvj**
Closes #70

### CODE REVIEW

File: lib/model/EcoscoreData.dart [hunk 1]
```diff
@@ -27,4 +27,7 @@ class EcoscoreData extends JsonObject {
 
   @override
   Map<String, dynamic> toJson() => _$EcoscoreDataToJson(this);
+
+  static Map<String, dynamic> toJsonHelper(EcoscoreData d) =>
+      d != null ? d.toJson() : {};
```
[the remark this answers is not in the document]
Comment (peterwvj) [reply lib/model/EcoscoreData.dart:32]: Given that the `ecoscore_data` field is only translated to JSON when it is different from `null` them "empty map" case should never occur:

```dart
writeNotNull(
      'ecoscore_data', EcoscoreData.toJsonHelper(instance.ecoscoreData));
```
... where `writeNotNull` is defined as follows:
```dart
writeNotNull(
      'ecoscore_data', EcoscoreData.toJsonHelper(instance.ecoscoreData));
```
So even though we change it to return `null` rather than the empty map it would not make a difference.

So I think it is fine to keep it as it is.

[the remark this answers is not in the document]
Comment (peterwvj) [reply lib/model/EcoscoreData.dart]: As a site note, I deleted my previous comment because I misunderstood but you were saying to begin with :) Sorry for the confusion. Anyway, I'll mark this as resolved. Let me know if you disagree.

File: lib/model/EcoscoreData.dart [hunk 2]
```diff
@@ -27,4 +27,7 @@ class EcoscoreData extends JsonObject {
 
   @override
   Map<String, dynamic> toJson() => _$EcoscoreDataToJson(this);
+
+  static Map<String, dynamic> toJsonHelper(EcoscoreData d) =>
```
Comment (FredJul) [inline lib/model/EcoscoreData.dart:31]: I see your problem and agree that it does not look normal to have a EcoscoreData instance in a json serialization output.

However, I'm a bit puzzled because: 
1/ the official sample seems to behave the same (line 39 of https://github.com/google/json_serializable.dart/blob/master/example/lib/example.g.dart we can see that it directly put the 'instance.orders' variable, without using toJson on it)

2/ I have an app which has the same "issue", but when I give the object to retrofit it will simply work. At the end, and I'm not sure why, the server receives a correct json.

So I wonder if it has not been designed this way, even if I find that quite surprising as well... Does someone has an answer?

File: test/json_product_generation_test.dart [hunk 3]
```diff
@@ -22,8 +23,20 @@ void main() {
...
-    print(JsonHelper.selectedImagesToJson(product.selectedImages));
     String json = jsonEncode(productMap);
     assert(json is String);
   });
-}
\ No newline at end of file
+
+  test('EcoscoreData JSON generation', () {
+    final product = Product();
+    product.productName = 'TestProduct';
```
Comment (FredJul) [inline test/json_product_generation_test.dart:32]: For the readability I would suggest to use the cascade operator (see https://dart.dev/guides/language/language-tour#cascade-notation- )

File: lib/model/EcoscoreData.dart (hunk 2 above)
Comment (FredJul) [reply lib/model/EcoscoreData.dart:31]: Ok, I just found an explanation there: https://github.com/google/json_serializable.dart/issues/702

We need to use 'explicitToJson: true' on all @JsonSerializable classes (including Product) to "fix" this issue.
But in explicitToJson documentation they say it's not really needed to do so since dart:convert will handle it.

So either we do nothing and accept this behavior, either we use explicitToJson everywhere.

Comment (peterwvj) [reply lib/model/EcoscoreData.dart:31]: Hi @FredJul , I am aware of the `explicitToJson` flag I intentionally did not add it. Currently, the SDK simply handles JSON generation differently (using the `toJson` helper function) and I wanted to fix the bug in a way that is consistent with respect to how JSON generation is handled for other classes/fields in the SDK.

Note, I'm not saying the way the SDK handles JSON generation is "right". In fact, using the `explicitToJson` could be a better way going forward. If we agree, at a later point, to use `explicitToJson` then we can add that using a separate pull request. That would require addressing this problem for all JSON classes in the SDK, which is outside the scope of this particular, PR.

For what is worth this PR is consistent with the way JSON generation is handled for other classes and fields in this SDK.

File: test/json_product_generation_test.dart (hunk 3 above)
Comment (peterwvj) [reply test/json_product_generation_test.dart]: I cleaned up the test. I was able to simply pass the field values via constructors.

File: lib/model/EcoscoreData.dart (hunk 2 above)
Comment (FredJul) [reply lib/model/EcoscoreData.dart:31]: Well, this PR seems to be consistent with the rest of the app, but I'm not fan of the added complexity (compared of doing nothing, or using `explicitToJson` if that's necessary).
However, I'm quite a new guy here and I may have missed something. Maybe others reviewers like @PrimaelQuemerais will agree with you.

**Review by PrimaelQuemerais — APPROVED** [review]

File: lib/model/EcoscoreData.dart (hunk 2 above)
Comment (PrimaelQuemerais) [reply lib/model/EcoscoreData.dart:31]: I approved it for now, we still need to write the best practices document for the project, we should probably discuss this at some point. I will take a look at the `explicitToJson` parameter

**Comment by peterwvj** [comment]
Thanks everyone for the feedback.
